# Generated by Django 4.0.2 on 2023-02-13 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroupreequest',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 22, 33, 48, 998072), null=True),
        ),
    ]
