# Generated by Django 4.0.2 on 2023-03-10 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krida', '0006_alter_bloodgroupreequest_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroupreequest',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krida.bloodgroupinfo'),
        ),
        migrations.AlterField(
            model_name='bloodgroupreequest',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 20, 17, 41, 930569), null=True),
        ),
    ]
